# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180418_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
