# Generated by Django 2.0.3 on 2018-04-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180401_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='picture',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
