# Generated by Django 2.0.3 on 2018-04-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180401_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
