# Generated by Django 2.0.4 on 2018-04-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
