# Generated by Django 2.0.4 on 2018-04-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
