# Generated by Django 2.0.4 on 2018-05-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.CharField(choices=[('freshman', 'Freshman'), ('sophomore', 'Sophomore'), ('junior', 'Junior'), ('senior', 'Senior')], default='freshman', max_length=9),
        ),
    ]
