# Generated by Django 2.0.4 on 2018-05-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180501_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], default='Freshman', max_length=9),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('Ratios, Proportions and Percents', 'Ratios, Proportions and Percents'), ('Number Theory and Divisibility', 'Number Theory and Divisibility'), ('Counting Basics and Probability', 'Counting Basics and Probability'), ('Quadratics', 'Quadratics'), ('Probability', 'Probability'), ('Advanced Geometrical Concepts', 'Advanced Geometrical Concepts'), ('Perimeter, Area and Surface Area', 'Perimeter, Area and Surface Area'), ('Logic, Sets and Venn Diagram', 'Logic, Sets and Venn Diagram'), ('Similarity', 'Similarity'), ('Coordiante Geometry', 'Coordiante Geometry'), ('Circles', 'Circles'), ('Trigonometry', 'Trigonometry'), ('Parametric Equations', 'Parametric Equations'), ('Theory of Equations', 'Theory of Equations')], default='Ratios, Proportions and Percents', max_length=20),
        ),
    ]
